### ISSUE TITLE
Merged ABIs and proxy contracts

### ISSUE THREAD

**Issue by droserasprout** [dipdup-io/dipdup#1002]
Should we convert `EvmContractConfig.abi` into tuple?

**Comment by juandiegocv27** [comment]
Hi @droserasprout, can I take thi issue?

**Comment by droserasprout** [comment]
Hi @juandiegocv27! Thanks for the interest. Actually, this ticket should be split into three:

1. EVM proxy contracts. Should be a pretty simple task - we have all the necessary data and heuristics is simple too.
2. Starknet (Cairo) proxy contracts. Much more cases, and we need to implement some logic in [Squid Network](https://github.com/subsquid/archive.py) first.
3. Merged ABIs. To be honest, I don't understand the use case for this feature, both in general and in our architecture. But it's implemented in [Ponder,](https://ponder.sh/docs/utilities/merge-abis) so I guess it make sense to at least try to understand its role.

Are you interested in Starknet specifically or just want to practice?

Coincidentally, I'm refactoring this part of code right now for the upcoming release. At the moment it's a huge mess and hardly pleasant to contribute to.

**Comment by droserasprout** [comment]
Closing in favor of #1092, #1093.
