### ISSUE TITLE
Cross-platform compatibility

### ISSUE THREAD

**Issue by droserasprout** [dipdup-io/dipdup#282]
**What feature would you like to see in DipDup?**

Full support of Windows, MacOS and non-Linux UNIX-like distros.

**Why do you need this feature, what's the use case?**

Some folks want to run DipDup on exotic OSes.

**Is there a workaround currently?**

WSL for win32, plug-and-pray for UNIX-like.

**Comment by droserasprout** [comment]
At least `asyncclick` doesn't work on win32. Need CI targets.

**Comment by m-kus** [comment]
MacOS: ok
WSL: should be ok, need to test

**Comment by droserasprout** [comment]
Windows support is extremely difficult to implement with our current stack. macOS is still our first-class citizen. Considering this one done.
