### ISSUE TITLE
Arbitrary hasura metadata customisations

### ISSUE THREAD

**Issue by 852Kerfunkle** [dipdup-io/dipdup#313]
I just added this to a metadata indexer related PR. See:

https://github.com/dipdup-net/go-lib/pull/4#issuecomment-1104558393
https://github.com/dipdup-net/go-lib/pull/4/commits/1b7297dc63c2848c24ba8c9c4ee0db3a8a55c08e
https://github.com/tz1and/metadata/commit/0724746ed388710738b72dfb5b517a7259208465

Basically, to allow running custom hasura api calls. Possibly to add other sources, remote schemas, relationships, or whatever else one might want to do with hasura.

**Comment by 852Kerfunkle** [comment]
Related: #289

**Comment by m-kus** [comment]
Reference: https://github.com/dipdup-io/metadata/tree/master/cmd/metadata/custom_hasura_config
Apply after all sql files executed and internal Hasura metadata is written
