### ISSUE TITLE
Allow to track SQL functions

### ISSUE THREAD

**Issue by m-kus** [dipdup-io/dipdup#450]
Latest Hasura allows to extend API with SQL functions in addition to views.
It can be used in cases when there's a need in parameterization, e.g. for status checks
https://hasura.io/docs/latest/schema/postgres/custom-functions/

Note that stable or immutable functions can be tracked as GQL queries, mutable functions only as GQL mutations.
Also, what should be the default REST method for mutations, POST or PUT/PATCH?

**Comment by droserasprout** [comment]
Duplicate: #313
