### ISSUE TITLE
Allow to set token/contract metadata to null

### ISSUE THREAD

**Issue by m-kus** [dipdup-io/dipdup#512]
Case: when Tezos domain is expired one need to invalidate contract metadata for each record associated with that domain.
We cannot delete the metadata item because it won't be indexed by third-party consumers in that case, just need to set it to NULL.

It can be done either by allowing `metadata=None` or by introducing `reset_contract_metadata(...)` helper.

Also `metadata` field should become nullable.

**Comment by droserasprout** [comment]
If only we could proceed without database migrations...

**Comment by droserasprout** [comment]
Closed by #644
