### ISSUE TITLE
`test_hasura` fails on macOS GHA runner

### ISSUE THREAD

**Issue by droserasprout** [dipdup-io/dipdup#546]
Missing docker.sock. Can't find a workaround.

**Comment by Wizard1209** [comment]
problem: postgres was not available from hasura container in local test environment
solution: docker port-forward both postgres and hasura to host network, make them available to each other through docker.internal.host and test code through localhost or 0.0.0.0

**Comment by Wizard1209** [comment]
the port-forward solution appears to be not reliable across different platforms, for now just skip the test for not Linux based platforms.
The future proposition is to move all testing environments to docker. Break 'make test' into three stages -- setup with docker-compose up three containers postgres, hasura; start dipdup(pytest run) container forward logs and status; docker-compose down

**Comment by droserasprout** [comment]
Chances that Hasura behaves differently depending on client environment are very low. After all, it's just a POST request. Let's keep things as is.
