### ISSUE TITLE
'HttpDatasource' object has no attribute '_default_http_config'

### ISSUE THREAD

**Issue by tezosmiami** [dipdup-io/dipdup#650]
**Steps to reproduce:**

- clone - https://github.com/tezosmiami/hicdex.git
- run readme commands

**What did you expect to happen:**
- learning. . .

**What actually happened:**
- errors - see logs

### Environment
- on ubuntu 22.04 server 

* **Python version:**
- with python 3.10.7:

* **DipDup version or commit hash:**
- 6.5.4

* **Database engine version:***
- postgres:14

* **Hasura version:**
 - 2.8.4

* **Are you in docker?**
* yes

* **Can you reproduce this issue on `master`?**
??

[error-log.txt](https://github.com/dipdup-io/dipdup/files/11192687/error-log.txt)
[models.txt](https://github.com/dipdup-io/dipdup/files/11192692/models.txt)
[config.txt](https://github.com/dipdup-io/dipdup/files/11192693/config.txt)

**Comment by droserasprout** [comment]
It's time to try one important thing. @all-contributors, add @tezosmiami for a bug.

**Comment by droserasprout** [comment]
@all-contributors add @tezosmiami for a bug.
