### ISSUE TITLE
Can't establish database connection

### ISSUE THREAD

**Issue by tezosmiami** [dipdup-io/dipdup#681]
**Steps to reproduce:**
clone - https://github.com/tezosmiami/hicdex.git
run readme commands

**What did you expect to happen:**
for it to run 
**What actually happened:**
hicdex-hicdex-1  | WARNING  dipdup.database      Can't establish database connection, attempt 0/60

able to connect to db with psql cli. . . 

### Environment
on ubuntu 22.04 server
* **Python version:**
3.10.7
* **DipDup version or commit hash:**
6.5.5
* **Database engine version:**
postgres:14
* **Hasura version:**
2.23.0
* **Are you in docker?**
yes
* **Can you reproduce this issue on `master`?**
yes

[dipdup_log.txt](https://github.com/dipdup-io/dipdup/files/11314439/dipdup_log.txt)

**Comment by droserasprout** [comment]
Doesn't seem like a bug to me. Please, use `config export` command as I've recommended earlier to ensure `database` section in your config is correct.

You can also add `print(ctx.config.database.connection_string)` to any handler or hook to get exact URI DipDup generates from config.
