### ISSUE TITLE
Indexes spawned at runtime don't start automatically (7.0.0rc2)

### ISSUE THREAD

**Issue by TristanAllaire** [dipdup-io/dipdup#767]
**Steps to reproduce:**
Everything is on Tezos.
I have a template defined in my dipdup.yml that I use in a handler. To use this template, I call the ctx.add_index() function.
I didn't change the implementation of this function from 6.5.9 to 7.0.0rc2.
The newly created index only starts when I restart the indexing (by using CTRL+C & dipdup run).
I think it was properly added in the DB as a new index but it isn't executed automatically. 

**What did you expect to happen:**
The new index runs and the operations start to get indexed

**What actually happened:**
Nothing happen. The handler doesn't crash but the index doesn't start. However, the newly created index (with ctx.add_index()) starts when I restart the indexer (CTRL+C & dipdup run)

### Environment

* **Python version:** 3.11.4
* **DipDup version or commit hash:** 7.0.0rc2
* **Database engine version:** Timescale 15
* **Hasura version:** 2.30.1
* **Are you in docker?** No

**Comment by droserasprout** [comment]
Hi! Currently, indexes from `ctx.add_index` start on the next synchronization loop. Have your "parent" index reached realtime before you've restarted the indexer?

**Comment by TristanAllaire** [comment]
Hi! I think yes!
I'm starting a huge template from a single index which is a contract origination. When the origination is done, I should reach realtime but the index won't start

**Comment by TristanAllaire** [comment]
Sorry @droserasprout my bad, actually I think it works. 
I just don't see the logs anymore. I didn't know the logging changed in version 7.0.0.

**Comment by droserasprout** [comment]
Am I understanding correctly that runtime indexes not start in your case even after config-defined ones has reached realtime state? Also, opened #770 and #771 to improve clarity.

**Comment by TristanAllaire** [comment]
Yes that's what's happening

**Comment by TristanAllaire** [comment]
Actually I just retested it now and this time, the runtime index won't run even if I restart manually and even if my config-defined one reached realtime

**Comment by droserasprout** [comment]
Thanks, gonna investigate.

**Comment by droserasprout** [comment]
Fixed in #784
