### ISSUE TITLE
"Transaction parameter is empty" error raised during indexing (7.0.0rc2)

### ISSUE THREAD

**Issue by TristanAllaire** [dipdup-io/dipdup#769]
**Steps to reproduce:**
Some of the entrypoints of the contracts I indexed don't require parameters to work. When operations are caught on them, they crash and return this error:

`FrameworkException('Transaction parameter is empty')`

I saw that it came from the `indexes/tezos_tzkt_operations/matcher.py` file.
Line 58:
```
if not operation_data.parameter_json:
  raise FrameworkException('Transaction parameter is empty')
``` 
This exception is raised even if the "parameter_json" attribute exists on the object but is equal to `{}`.
In order to fix the issue, I replace the condition with:
```
if operation_data.parameter_json is None:
```

Doing this fixed the crash on my side but is it what you were trying to check in this file?

### Environment

* **Python version:** 3.11.4
* **DipDup version or commit hash:** 7.0.0rc2
* **Database engine version:** Timescale15
* **Hasura version:** 2.30.1
* **Are you in docker?** No
* **Can you reproduce this issue on `next`?** Yes

**Comment by droserasprout** [comment]
Yup, that's exactly what you think it is, an incorrect check. Thanks!
