### ISSUE TITLE
Config reference in docs is unreadable

### ISSUE THREAD

**Issue by droserasprout** [dipdup-io/dipdup#782]
Also missing ToC

**Comment by Wizard1209** [comment]
We want reference to be included in common docs deploying pipeline and to have consistent formatting with the rest of the doc to make further improvements

We have three types of references
1. Python references - most important is context(ctx) reference and second one is config reference
examples: 
https://flask.palletsprojects.com/en/3.0.x/api/
https://docs.djangoproject.com/en/4.2/ref/
2. CLI reference
examples:
https://docs.docker.com/engine/reference/commandline/cli/
3. YAML reference for dipdup.yaml
https://docs.docker.com/compose/compose-file/compose-file-v3/#service-configuration-reference

Key features for all references:
1. Frontend should be generated from intermediate format(output of tools such as Sphinx and https://github.com/cloudflare/doca)
2. Support for current search
3. Support cross-referencing and content hierarchy

**Comment by droserasprout** [comment]
They are pretty nice now.
