### ISSUE TITLE
"Processing typed transaction, but parameter_json is None" error raised during indexing (7.0.0rc4)

### ISSUE THREAD

**Issue by TristanAllaire** [dipdup-io/dipdup#812]
**Steps to reproduce:**
We had a similar issue before here: https://github.com/dipdup-io/dipdup/issues/769
The **Steps to reproduce:** are similar between the two errors.
However this time I got the error with an entrypoint that has an `option` as a parameter (in this case, the parameter is either a String or None/null). 

I was able to fix the issue locally by replacing this in `src/dipdup/indexes/tezos_tzkt_operations/matcher.py` line 57:
```python
if operation_data.parameter_json is None:
    raise FrameworkException('Processing typed transaction, but parameter_json is None')
```
into this:
```python
if not hasattr(operation_data, 'parameter_json'):
    raise FrameworkException('Processing typed transaction, but parameter_json is None')
```

### Environment

* **Python version:** 3.11.4
* **DipDup version or commit hash:** 7.0.0rc4
* **Database engine version:** TimescaleDB 15
* **Hasura version:** 2.30.1
* **Are you in docker?** No
* **Can you reproduce this issue on `next`?** Yes

**Comment by Wizard1209** [comment]
I wasn't able to reproduce this error, I have indexed the call of operation [mint in plenty](https://better-call.dev/mainnet/KT1GRSvLoikDsXujKgZPsGLX8k8VvR2Tq95b/interact/mint). Do you have any examples?
The type of operation_data should have an attribute parameter_json, so your fix has worked in some not straightway.

**Comment by TristanAllaire** [comment]
I had my issue when I tried to index the `%councilActionSetBaker` entrypoint of this contract `KT1KZHRFrvAYD3WPXTJVGbS36BShjcoivTTe` on the Ghostnet. 
This parameter type is an option that can either be equal to a `key_hash` or `None`.
When I index it while setting `None`, I think I'm getting `None` too in the parameter_json.
