### ISSUE TITLE
Data types in SubsquidEventData and EvmNodeLogData are different

### ISSUE THREAD

**Issue by scottincrypto** [dipdup-io/dipdup#837]
**Steps to reproduce:**
Log events using subsquid archive -> event_index & transaction_index are type int, topics is tuple(str)
Log events using live evm node -> event_index & transaction_index are type str, topics is list(str)

Also, it appears as though the block number is called block_number in EvmNodeData, and level in SubsquidEventData 

**What did you expect to happen:**
Consistent data types & variable names between these as they are interchangeable due to:
```
class SubsquidEvent(Generic[PayloadT]):
    data: SubsquidEventData | EvmNodeLogData
    payload: PayloadT
```

**What actually happened:**
See above - data types are different, and block number is a different variable name

I'm happy to have a go at a PR for this issue, let me know which direction you'd like it to go (as per SubsquidEventData or EvmNodeLogData)

### Environment

* **Python version: Python 3.11.4**
* **DipDup version or commit hash: 7.0.0rc5**
* **Database engine version: not relevant**
* **Hasura version: not relevant**
* **Are you in docker? No**
* **Can you reproduce this issue on `next`? yes**

**Comment by droserasprout** [comment]
Thanks, @scottincrypto! I've pushed a fix in linked PR; give it a look if you have spare time.

**Comment by scottincrypto** [comment]
Thanks @droserasprout , that's fixed it nicely.  Appreciate the quick fix, thanks!

**Comment by scottincrypto** [comment]
Closed
