### ISSUE TITLE
Use "X as Y" for dipdup imports in callbacks

### ISSUE THREAD

**Issue by droserasprout** [dipdup-io/dipdup#993]

**Comment by ibsule** [comment]
Hi. @droserasprout, please can you add more explanation and context to this so I can attempt it?

**Comment by droserasprout** [comment]
Hi @princeibs! This ticket is for our team to track progress on task. I have created a "help wanted" tag to track tickets suitable for external contributors and marked some.

https://github.com/dipdup-io/dipdup/issues?q=is%3Aopen+label%3A%22help+wanted%22+sort%3Aupdated-desc
